# arguments for dataset
dataset: pascal
nclass: 9
# nclass: 3
crop_size: 512
data_root: data/ms-tcl

# arguments for training
epochs: 300
batch_size: 2 # per GPU x 4 GPUs
lr: 0.0005
lr_multi: 10.0
criterion:
  name: CELoss
  kwargs:
    ignore_index: 255
conf_thresh: 0.95

# arguments for model
model: deeplabv3plus
backbone: resnet50 
replace_stride_with_dilation: [False, False, True]
dilations: [6, 12, 18]
